name: Update FuelWatch

on:
  schedule:
    - cron: "30 12 * * 3"   # Miércoles 09:30 Chile aprox (12:30 UTC). Ajusta según horario de verano.
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Update CSV
        run: |
          python update_weekly.py

      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add data/variaciones_semana.csv
          git commit -m "chore: weekly update" || echo "No changes"
          git push
